image: docker:latest

services:
  - docker:19.03.1-dind

variables:
  FINAL_IMAGE_NAME: urothis/dex:latest

stages:
  - Build Disdex
  - Build Module
  - Build image
  - Push to Docker Hub

golang build:
  stage: Build Disdex
  image: golang:1.13.0  
  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go build -o disdex
  artifacts:
    paths:
    - disdex
    expire_in: 1 week
  
module build:
  stage: Build Module
  image: squattingmonk/nasher:latest
  script:
    nasher pack
  artifacts:
    paths:
    - server/modules/DungeonEternalX.mod
    expire_in: 1 week

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t $FINAL_IMAGE_NAME .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $FINAL_IMAGE_NAME && docker image rm $FINAL_IMAGE_NAME