image: docker:latest

services:
  - docker:19.03.1-dind

stages:
  - Test
  - Build
  - Deploy

variables:
  FINAL_PROD_NWSERVER_IMAGE_NAME: registry.gitlab.com/urothis/nwn-module-dungeoneternalx/prod-nwserver
  FINAL_DEV_NWSERVER_IMAGE_NAME: registry.gitlab.com/urothis/nwn-module-dungeoneternalx/dev-nwserver
  FINAL_DISDEX_IMAGE_NAME: registry.gitlab.com/urothis/nwn-module-dungeoneternalx/disdex
  MODULE_NAME: DungeonEternalX.mod
  MODULE_REPO: https://github.com/urothis/nwn-module-DungeonEternalX.git
  FOLDER_NAME: nwn-module-DungeonEternalX

include:
  - local: .gitlab/ci/disdex.gitlab-ci.yml
  - local: .gitlab/ci/prod-nwserver.gitlab-ci.yml