image: docker:latest

services:
  - docker:19.03.1-dind

variables:
  FINAL_IMAGE_NAME: registry.gitlab.com/urothis/nwn-module-dungeoneternalx:latest

stages:
  - Build
  - Deploy

build:disdex:
  stage: Build
  image: golang:1.13.0  
  script:
    - cd disdex
    - go build -o disdexBinary
    - mv disdexBinary $CI_PROJECT_DIR/disdexBinary
  artifacts:
    paths:
    - disdexBinary
    expire_in: 1 week
 
build:dex:
  stage: Build
  image: 
    name: squattingmonk/nasher:latest
    entrypoint: [""]
  script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 -y
    - git clone https://github.com/urothis/nwn-module-DungeonEternalX.git
    - cd nwn-module-DungeonEternalX
    - "nasher config --nssFlags:'-n /nwn/data -o'"
    - nasher pack
    - cp DungeonEternalX.mod $CI_PROJECT_DIR/DungeonEternalX.mod
  artifacts:
    paths:
    - DungeonEternalX.mod
    expire_in: 1 week

deploy:docker:
  stage: Deploy
  only:
  - master
  script:
  - env | sed '/^DOCKER_ENV_CI_SERVER_TLS_CA_FILE=/,/^$/d' > gitlab.env
  - docker build -t $FINAL_IMAGE_NAME .
  - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  - docker push $FINAL_IMAGE_NAME && docker image rm $FINAL_IMAGE_NAME