image: docker:latest

services:
  - docker:19.03.1-dind

stages:
  - Build
  - Deploy

variables:
  FINAL_NWSERVER_IMAGE_NAME: registry.gitlab.com/urothis/nwn-module-dungeoneternalx/nwserver:latest
  FINAL_DISDEX_IMAGE_NAME: registry.gitlab.com/urothis/nwn-module-dungeoneternalx/disdex:latest

include:
  - local: .gitlab/ci/disdex.gitlab-ci.yml
  - local: .gitlab/ci/nwserver.gitlab-ci.yml