image: docker:stable

variables:
  IMAGE_NAME: urothis/nwn-module-DungeonEternalX:latest

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t $IMAGE_NAME .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $IMAGE_NAME && docker image rm $IMAGE_NAME