image: docker:latest

services:
  - docker:19.03.1-dind

variables:
  FINAL_IMAGE_NAME: urothis/dex:latest

stages:
  - Build
  - Staging
  - Deploy

build:disdex:
  stage: Build
  image: golang:1.13.0  
  script:
    - cd disdex
    - go build -o _disdex
  artifacts:
    paths:
    - _disdex
    expire_in: 1 week
 
build:dex:
  stage: Build
  image: 
    name: squattingmonk/nasher:latest
    entrypoint: [""]
  script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 -y
    - git clone https://github.com/urothis/nwn-module-DungeonEternalX.git
    - cd nwn-module-DungeonEternalX
    - nasher pack
  artifacts:
    paths:
    - server/DungeonEternalX.mod
    expire_in: 1 week

build:docker:
  stage: Staging
  only:
  - master
  script:
  - docker info
  - docker build -t $FINAL_IMAGE_NAME .

docker push:
  stage: Deploy
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $FINAL_IMAGE_NAME && docker image rm $FINAL_IMAGE_NAME